name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: conference_101719.tex
          working_directory: paper/
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: run bibtex 
        uses: dante-ev/latex-action@latest
        with:
          root_file: conference_101719.aux
          working_directory: paper/
          compiler: bibtex
          args:
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: conference_101719.tex
          working_directory: paper/
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
